name: Deploy Site
on: [push]
jobs:
  build-website:
    name: Website build
    runs-on: ubuntu-latest
    # https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-first-deployment-with-github_token
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install AsciiDoctor
      run: sudo apt-get install asciidoctor
    - name: Run AsciiDoctor
      run: asciidoctor -b html5 -R . -D public '**/*.adoc'
    - name: Upload HTML Pages
      if: ${{ github.ref_name == 'master' && github.event_name != 'pull_request' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: www
        publish_dir: ./public
